{
 "title": "Self-driving",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Состояние запуска",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "robot_control_state", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Частота обработки данных сенсоров",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "lidar_hz", "legendFormat": "__auto" },
    { "expr": "camera_hz", "legendFormat": "__auto" },
    { "expr": "gnss_hz", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Скорость",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Передача",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "transmission", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Угол поворота руля",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "steering", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TrackMap",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "lat", "legendFormat": "__auto" },
    { "expr": "lon", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Скорость",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "speed", "legendFormat": "__auto" }
   ]
  }
 ]
}