#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'webots-ros2-suv==2023.0.1','console_scripts','field_follower'
__requires__ = 'webots-ros2-suv==2023.0.1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('webots-ros2-suv==2023.0.1', 'console_scripts', 'field_follower')()
    )
