ARG BASE_IMAGE=osrf/ros:humble-desktop
FROM $BASE_IMAGE

ARG DEBIAN_FRONTEND=noninteractive
ARG UID=1000

# User
RUN useradd -d /ulstu -m \
    -u $UID -U \
    -s /usr/bin/bash \
    -G dialout \
    -c "Ulstu Robotics" ulstu && \
    echo "ulstu ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Essentials
RUN apt-get update && apt-get install --no-install-recommends -y -o Dpkg::Options::="--force-overwrite" \
    ros-humble-navigation2 \
    ros-humble-nav2-bringup \
    ros-humble-rviz2 \
    ros-humble-teleop-twist-keyboard \
    ros-humble-dynamixel-sdk \
    ros-humble-can-msgs \
    ros-humble-ruckig \
    ros-humble-laser-filters \
    ros-humble-domain-bridge \
    ros-humble-rmw-cyclonedds-cpp \
    ros-humble-ros2-control \
    ros-humble-ros2-controllers \
    ros-humble-rqt-common-plugins \
    ros-humble-webots-ros2 \
    ros-humble-nav2-common \
    ros-humble-dynamixel-workbench-toolbox \
    ros-humble-behaviortree-cpp \
    libopencv-dev \
    python3-pip \
    python3-pil \
    alsa \
    libxshmfence1 \
    libgtk-3-dev \
    git \
    git-lfs \
    curl \
    wget \
    vim \
    rsync \
    dialog \
    fuse

RUN apt install --yes xvfb ffmpeg lsb-release g++ make libavcodec-extra libglu1-mesa libegl1 libxkbcommon-x11-dev libxcb-keysyms1 libxcb-image0 libxcb-icccm4 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcomposite-dev libxtst6 libnss3    

RUN curl -sL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get update && apt-get install -y nodejs

#HOTFIX: https://github.com/ros-controls/ros2_controllers/issues/482
RUN wget -O /tmp/diff_drive_controller.deb http://snapshots.ros.org/humble/2022-11-23/ubuntu/pool/main/r/ros-humble-diff-drive-controller/ros-humble-diff-drive-controller_2.12.0-1jammy.20221108.202153_amd64.deb && \
    apt install -y --allow-downgrades /tmp/diff_drive_controller.deb && \
    rm -f /tmp/diff_drive_controller.deb

# User config
COPY ./config/bashrc /tmp/bashrc
COPY --chmod=755 ./config/setup.sh /usr/bin/

RUN cat /tmp/bashrc >> /ulstu/.bashrc && \
    rm -f /tmp/bashrc && \
    mkdir  -p /ulstu/ros2_ws/src && \
    chown -R ulstu:ulstu /ulstu

#RUN sudo -E rosdep init 
RUN apt-get install -y python3-vcstool
RUN rosdep --rosdistro "${ROS_DISTRO}" update 
RUN cd /ulstu/ros2_ws && yes | rosdep --rosdistro "${ROS_DISTRO}" install -r --from-paths src --ignore-src

USER ulstu
WORKDIR /ulstu/ros2_ws

EXPOSE 8008
