states_dir: "robocross/"
states:
  start: "StartState.py"
  moving: "MovingState.py"
  astarmoving: "AStarMovingState.py"
  gpsfollow: "GPSFollowState.py"
  lanefollow: "LaneFollowState.py"
  paused: "PausedState.py"
  stopped: "StoppedState.py"
  emergency: "EmergencyState.py"
  turn: "TurnState.py"
workers:
  # lightswitch: "LightSwitchDetectorWorker.py"
  # roadsign: "RoadSignDetectorWorker.py"
  # ipm: "IPMWorker.py"
  # semanticsegmentation: "SemanticSegmentationWorker.py"
  # lanelinedetection: "LaneLineDetectionWorker.py"
  pathplanning: "PathPlanningWorker.py"
  behavioranalysis: "BehavioralAnalysisWorker.py"
  reedsshepp: "ReedsSheppPlanningWorker.py"
  agronavigator: "AgronavigatorWorker.py"
  # roadmarkingdetection: "RoadMarkingDetectionWorker.py"
workerstates:
  start: []
  moving: [] # "pathplanning"
  astarmoving: ["pathplanning", "agronavigator"]
  lanefollow: ["pathplanning", "agronavigator"]
  gpsfollow: ["agronavigator"] #, "pathplanning"]
  stopped: []
  paused: []
  turn: ["reedsshepp"]
  emergency: []
transitions:
  start:
    start_move: ["gpsfollow"] # "gpsfollow"
    stop: ["stopped"]
    pause: ["paused"]
  gpsfollow:
    start_astar: ["astarmoving"]
    start_move: ["moving"]
    # start_gps_follow: ["gpsfollow"] 
    # start_lane_follow: ["lanefollow"]
    pause: ["paused"]
    stop: ["stopped", "emergency"]
    turn: ["turn"]
  astarmoving:
    start_gps_follow: ["gpsfollow"]
    pause: ["paused"]
    stop: ["stopped", "emergency"]
    turn: ["turn"]
  moving:
    start_gps_follow: ["gpsfollow"]
    start_lane_follow: ["lanefollow"]
    stop: ["stopped", "emergency"]
    turn: ["turn"]
  lanefollow:
    start_gps_follow: ["gpsfollow"] 
    start_move: ["moving"]
    stop: ["stopped", "emergency"]
    turn: ["turn"]
  paused:
    start_move: ["gpsfollow"]
  stopped:
    start_move: ["gpsfollow"]
  emergency:
    reset: ["start"]
  turn:
    start_move: ["moving"]
    stop: ["stopped", "emergency"]
map-elements:
  - element:
    id: "field"
    name: !!str Поле для обработки 
    ol-type: !!str Polygon
    color: !!str aaaa11
  - element:
    id: "parking"
    name: !!str Зона парковки
    ol-type: !!str Polygon
    color: !!str ff1111
  - element:
    id: "loading"
    name: !!str Зона погрузки расходников 
    ol-type: !!str Polygon
    color: !!str 11ff11
  - element:
    id: "refueling"
    name: !!str Зона заправки топлива 
    ol-type: !!str Polygon
    color: !!str 111111
  - element:
    id: "moving"
    name: !!str Дорога для движения
    ol-type: !!str LineString
    color: !!str 1111ff